import "./globals.css";
import "@mantine/core/styles.css";
import "@mantine/dates/styles.css";

import { Inter } from "next/font/google";
import { MantineProvider, ColorSchemeScript, Container } from "@mantine/core";
import Provider from "../components/sections/Provider";
import NavbarComponent from "@/components/sections/NavbarComponent";
import { getServerSession } from "next-auth";
import { authOptions } from "@/libs/auth";
import AffixPartials from "@/components/partials/AffixPartials";
import { Notifications } from "@mantine/notifications";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Home",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  const session = getServerSession(authOptions);
  return (
    <html lang="en">
      <head>
        <ColorSchemeScript />
      </head>
      <body>
        <Provider>
          <MantineProvider defaultColorScheme="light">
            <Notifications />
            {/* <NavbarComponent session={session} /> */}
            {children}
            <AffixPartials />
          </MantineProvider>
        </Provider>
      </body>
    </html>
  );
}
