import React from "react";

export const metadata = {
  title: "Post - Dashboard",
  description: "Generated by create next app",
};
export default function layout({ children }) {
  return <div>{children}</div>;
}
