import AffixPartials from "@/components/partials/AffixPartials";
import React from "react";

export const metadata = {
  title: "Home Admin - Dashboard",
  description: "Generated by create next app",
};

export default function AdminLayout({ children }) {
  return (
    <>
      {children}
      {/* <AffixPartials /> */}
    </>
  );
}
